### ISSUE TITLE
Pages (and probably others) need primary key ID attributes to be used in URLs.

### ISSUE THREAD

**Issue by brenns10** [jpcjr/corvid#24]

**Comment by jpcjr** [comment]
Projects and Categories should stay as unique for passing around URLs. Though, Pages & Posts should be accessible by one of, in order of preference:
- Django's automatic `id` field - built-in, somewhat memorable, not relevant to the title
- a random string (like Gyfcat) - more memorable, but still not relevant to the title
- a UUID - too long

...because:
- duplicate titles should be permissible (will require changes to site generation), and
- posts/pages should be accessible from the same URL after title changes

**Comment by brenns10** [comment]
Page titles may also need to remain unique, but I do believe posts don't need to be unique.

Modifying titles will be annoying for URLs and updating forms.
