### ISSUE TITLE
Allow Pages, Post with same names

### ISSUE THREAD

**Issue by jpcjr** [jpcjr/corvid#59]
We reference these by ID now. No need to get integrity errors when we create a page / post with a duplicate name. We'll need to update Site Generation to handle multiple names, but that's literally just a Counter object.

**Comment by brenns10** [comment]
Just to pile on, when we do the Counter in Site Generation, we need to make sure that we append the count to the slugified title, even when there's only one instance of that title.  Otherwise we could run into the following situation:

1. User creates page "Home".  The generated filename is "home.html".
2. User creates page "Home".  The generated filename is "home-1.html".
3. User creates page "Home 1".  The generated filename is "home-1.html".  Name clash!

**Comment by jpcjr** [comment]
Well, the approach I was thinking of here was:

1. Generate title (e.g. slugify)
2. Increment `Counter`
3. If count > 1, append count to item. Repeat.

This algorithm is guaranteed to terminate for a finite number of pages.

Then your sequence of events becomes:
1. create "Home" -> `home.html`
2. create "Home" -> `home-2.html`
2. create "Home 2" -> `home-2-2.html`
