### ISSUE TITLE
Title is wrong

### ISSUE THREAD

**Issue by ajm188** [jpcjr/corvid#79]
It says "Corvid - Static Site Generator" while @jpcjr says it should say "Corvid - Static Site Generation Tool".

This is a P0 and should be fixed *immediately*.

**Comment by jpcjr** [comment]
More accurately, we're not really static site generator; that's why we use Pelican. Perhaps our slogan, **"Websites Made Easy"** would be better? Or maybe even some descriptor of the page (e.g. Project Home, Edit Category)?

**Comment by brenns10** [comment]
On the home page, I think "Corvid - Static Site Generator" is appropriate (but @jpcjr's alternative would also work).  I don't think the semantic concern about whether we actually generate the site is important to an end user.  Especially since our target users probably wouldn't understand the distinction.

However, I totally agree that on other pages, the titles should be a descriptor of the page, similar to how GitHub or any other site does it.  For instance, on the TSwizzle project home, the title should be something like

> TSwizzle &#8226; Corvid

Or

> taytay/TSwizzle &#8226; Corvid

Similar title ideas for different secenarios:
- Add post: "Create Post &#8226; TSwizzle &#8226; Corvid"
- Edit post: "Blank Space (editing) &#8226; TSwizzle &#8226; Corvid"
- Project settings: "TSwizzle Settings &#8226; Corvid"

etc.

Separator character I'm using now is the bullet character, we could also consider pipe, hyphen, or something else.
